//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 06:48:51 PM IST 
//


package sample.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="addendum" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="name1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="name3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="name4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="name5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="name6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="name7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="name8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addendum"
})
@XmlRootElement(name = "request")
public class Request {

    protected List<Request.Addendum> addendum;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the addendum property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addendum property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddendum().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Request.Addendum }
     * 
     * 
     */
    public List<Request.Addendum> getAddendum() {
        if (addendum == null) {
            addendum = new ArrayList<Request.Addendum>();
        }
        return this.addendum;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="name1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="name2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="name3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="name4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="name5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="name6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="name7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="name8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "name1",
        "name2",
        "name3",
        "name4",
        "name5",
        "name6",
        "name7",
        "name8"
    })
    public static class Addendum {

        protected String name;
        protected String name1;
        protected String name2;
        protected String name3;
        protected String name4;
        protected String name5;
        protected String name6;
        protected String name7;
        protected String name8;
        @XmlAttribute(name = "type")
        protected String type;
        @XmlAttribute(name = "key")
        protected String key;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the name1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName1() {
            return name1;
        }

        /**
         * Sets the value of the name1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName1(String value) {
            this.name1 = value;
        }

        /**
         * Gets the value of the name2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName2() {
            return name2;
        }

        /**
         * Sets the value of the name2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName2(String value) {
            this.name2 = value;
        }

        /**
         * Gets the value of the name3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName3() {
            return name3;
        }

        /**
         * Sets the value of the name3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName3(String value) {
            this.name3 = value;
        }

        /**
         * Gets the value of the name4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName4() {
            return name4;
        }

        /**
         * Sets the value of the name4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName4(String value) {
            this.name4 = value;
        }

        /**
         * Gets the value of the name5 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName5() {
            return name5;
        }

        /**
         * Sets the value of the name5 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName5(String value) {
            this.name5 = value;
        }

        /**
         * Gets the value of the name6 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName6() {
            return name6;
        }

        /**
         * Sets the value of the name6 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName6(String value) {
            this.name6 = value;
        }

        /**
         * Gets the value of the name7 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName7() {
            return name7;
        }

        /**
         * Sets the value of the name7 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName7(String value) {
            this.name7 = value;
        }

        /**
         * Gets the value of the name8 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName8() {
            return name8;
        }

        /**
         * Sets the value of the name8 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName8(String value) {
            this.name8 = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the key property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKey() {
            return key;
        }

        /**
         * Sets the value of the key property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKey(String value) {
            this.key = value;
        }

    }

}
